<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');header('Referrer-Policy: no-referrer');
const SESSION_TTL=1800;const MAX_BODY=8192;$storageDir=__DIR__.'/../storage';$sessionsFile=$storageDir.'/sessions.json';$rateFile=$storageDir.'/admin-rate-limits.json';
function respond(int $status,array $body){http_response_code($status);echo json_encode($body,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function same_origin():bool{$origin=$_SERVER['HTTP_ORIGIN']??'';if($origin==='')return true;$host=strtolower((string)preg_replace('/:\d+$/','',$_SERVER['HTTP_HOST']??''));$originHost=strtolower((string)parse_url($origin,PHP_URL_HOST));return $host!==''&&hash_equals($host,$originHost);}
function token():string{$header=$_SERVER['HTTP_AUTHORIZATION']??'';return preg_match('/^Bearer\s+([a-f0-9]{64})$/i',trim($header),$m)===1?$m[1]:'';}
function valid(array $session):bool{return (int)($session['expires_at']??0)>time();}
function load_json(string $file):array{$data=json_decode((string)@file_get_contents($file),true);return is_array($data)?$data:[];}
function save_json(string $file,array $data):void{$json=json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT);if($json===false||file_put_contents($file,$json."\n",LOCK_EX)===false)respond(500,['ok'=>false,'error'=>'Не удалось сохранить данные']);@chmod($file,0600);}
if(!same_origin())respond(403,['ok'=>false,'error'=>'Источник запроса не разрешён']);if((int)($_SERVER['CONTENT_LENGTH']??0)>MAX_BODY)respond(413,['ok'=>false,'error'=>'Слишком большой запрос']);if(!is_dir($storageDir)&&!mkdir($storageDir,0700,true)&&!is_dir($storageDir))respond(500,['ok'=>false,'error'=>'Хранилище недоступно']);
$method=$_SERVER['REQUEST_METHOD']??'GET';$action=$_GET['action']??($method==='POST'?'login':'verify');
if($method==='POST'&&$action==='login'){$loginExpected=(string)getenv('ADMIN_LOGIN');$hash=(string)getenv('ADMIN_PASSWORD_HASH');$secret=(string)getenv('APP_SECRET');if($loginExpected===''||$hash===''||$secret==='')respond(503,['ok'=>false,'error'=>'Доступ администратора не настроен']);$input=json_decode((string)file_get_contents('php://input'),true);if(!is_array($input))respond(400,['ok'=>false,'error'=>'Некорректный запрос']);$login=trim((string)($input['login']??''));$password=(string)($input['password']??'');$now=time();$ipHash=hash_hmac('sha256',(string)($_SERVER['REMOTE_ADDR']??''),$secret);$rates=load_json($rateFile);$rates[$ipHash]=array_values(array_filter((array)($rates[$ipHash]??[]),function($t)use($now){return (int)$t>$now-900;}));if(count($rates[$ipHash])>=5)respond(429,['ok'=>false,'error'=>'Слишком много попыток. Подождите 15 минут']);if($login===''||$password===''||!hash_equals($loginExpected,$login)||!password_verify($password,$hash)){$rates[$ipHash][]=$now;save_json($rateFile,$rates);usleep(350000);respond(401,['ok'=>false,'error'=>'Неверный логин или пароль']);}unset($rates[$ipHash]);save_json($rateFile,$rates);$sessions=load_json($sessionsFile);foreach($sessions as $key=>$session){if(!is_array($session)||!valid($session))unset($sessions[$key]);}$access=bin2hex(random_bytes(32));$sessions[$access]=['admin_id'=>1,'username'=>$loginExpected,'created_at'=>$now,'expires_at'=>$now+SESSION_TTL,'ip_hash'=>$ipHash];save_json($sessionsFile,$sessions);respond(200,['ok'=>true,'token'=>$access,'expires_in'=>SESSION_TTL,'admin'=>['username'=>$loginExpected]]);}
$access=token();$sessions=load_json($sessionsFile);$session=$access!==''&&isset($sessions[$access])&&is_array($sessions[$access])?$sessions[$access]:null;if(!is_array($session)||!valid($session)){if($access!==''&&isset($sessions[$access])){unset($sessions[$access]);save_json($sessionsFile,$sessions);}respond(401,['ok'=>false,'error'=>'Требуется вход']);}
if($method==='GET'&&$action==='verify')respond(200,['ok'=>true,'admin'=>['username'=>$session['username']??'admin'],'expires_at'=>$session['expires_at']]);
if($method==='POST'&&$action==='logout'){unset($sessions[$access]);save_json($sessionsFile,$sessions);respond(200,['ok'=>true]);}
respond(405,['ok'=>false,'error'=>'Метод не разрешён']);
