<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');header('Referrer-Policy: no-referrer');
$storage=__DIR__.'/../storage';$file=$storage.'/leads.json';
function finish(int $status,array $body){http_response_code($status);echo json_encode($body,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function same_origin():bool{$origin=$_SERVER['HTTP_ORIGIN']??'';if($origin==='')return true;$host=strtolower((string)preg_replace('/:\d+$/','',$_SERVER['HTTP_HOST']??''));return $host!==''&&hash_equals($host,strtolower((string)parse_url($origin,PHP_URL_HOST)));}
function bearer():string{$header=$_SERVER['HTTP_AUTHORIZATION']??'';return preg_match('/^Bearer\s+([a-f0-9]{64})$/i',trim($header),$m)===1?$m[1]:'';}
function auth(string $storage):void{$key=bearer();$sessions=json_decode((string)@file_get_contents($storage.'/sessions.json'),true);$session=is_array($sessions)&&isset($sessions[$key])&&is_array($sessions[$key])?$sessions[$key]:null;if(!is_array($session)||(int)($session['expires_at']??0)<=time())finish(401,['ok'=>false,'error'=>'Требуется вход']);}
function read_leads(string $file):array{$data=json_decode((string)@file_get_contents($file),true);if(!is_array($data))return [];$data=$data['leads']??$data;return is_array($data)?array_values(array_filter($data,'is_array')):[];}
function write_leads(string $file,array $leads):void{$json=json_encode(array_values($leads),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT);if($json===false||file_put_contents($file,$json,LOCK_EX)===false)finish(500,['ok'=>false,'error'=>'Не удалось сохранить заявки']);@chmod($file,0600);}
if(!same_origin())finish(403,['ok'=>false,'error'=>'Источник запроса не разрешён']);auth($storage);$method=$_SERVER['REQUEST_METHOD']??'GET';$action=$_GET['action']??'list';
if($method==='GET'&&$action==='list'){$leads=read_leads($file);usort($leads,function($a,$b){return strcmp((string)($b['created_at']??''),(string)($a['created_at']??''));});finish(200,['ok'=>true,'leads'=>array_slice($leads,0,500),'total'=>count($leads)]);}
if($method==='POST'&&in_array($action,['status','delete'],true)){$input=json_decode((string)file_get_contents('php://input'),true);$id=is_array($input)?trim((string)($input['id']??'')):'';if($id===''||strlen($id)>80)finish(400,['ok'=>false,'error'=>'Некорректный ID']);$leads=read_leads($file);$found=false;$result=[];foreach($leads as $lead){if(hash_equals((string)($lead['id']??''),$id)){$found=true;if($action==='delete')continue;$status=(string)($input['status']??'');if(!in_array($status,['new','processing','completed','rejected'],true))finish(400,['ok'=>false,'error'=>'Некорректный статус']);$lead['status']=$status;$lead['updated_at']=gmdate('c');}$result[]=$lead;}if(!$found)finish(404,['ok'=>false,'error'=>'Заявка не найдена']);write_leads($file,$result);finish(200,['ok'=>true]);}
finish(405,['ok'=>false,'error'=>'Метод не разрешён']);
